# Generated by Django 3.1.3 on 2021-01-21 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
                ('movie', models.FileField(upload_to='videos/')),
                ('details', models.TextField(blank=True)),
                ('genre', models.CharField(choices=[('1', 'Action'), ('2', 'Comedy'), ('3', 'Drama'), ('4', 'Fantasy'), ('5', 'Mystery'), ('6', 'Romance'), ('7', 'Horror'), ('8', 'Teen')], default='1', max_length=20)),
                ('poster', models.ImageField(upload_to='images/poster/')),
            ],
            options={
                'verbose_name': 'movie',
                'verbose_name_plural': 'movies',
            },
        ),
        migrations.CreateModel(
            name='PostsForMainMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=40)),
                ('post_author', models.CharField(max_length=50)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('post_description', models.TextField()),
                ('post_full_description', models.TextField()),
                ('post_image', models.ImageField(upload_to='images/postsformainmenu/')),
            ],
        ),
        migrations.CreateModel(
            name='Premyera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premyera_caption', models.CharField(max_length=100)),
                ('premyera_image', models.ImageField(upload_to='images/premyera/')),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_title', models.CharField(max_length=100)),
                ('caption', models.TextField()),
                ('slider_image', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
    ]
