# Generated by Django 2.2.16 on 2021-01-18 04:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='slider_title',
            field=models.CharField(default=datetime.datetime(2021, 1, 18, 4, 36, 6, 529655), max_length=100),
            preserve_default=False,
        ),
    ]
