# Generated by Django 3.1.3 on 2021-01-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardsForTrailer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_caption', models.CharField(max_length=200)),
                ('card_image', models.ImageField(upload_to='images/imagesforcards/')),
            ],
        ),
        migrations.RemoveField(
            model_name='movies',
            name='poster',
        ),
    ]
