# Generated by Django 2.2.16 on 2021-01-18 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_slider_slider_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='slider_image',
            field=models.ImageField(upload_to='movies/images/'),
        ),
    ]
