# Generated by Django 3.1.3 on 2021-01-27 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20210122_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='poster',
            field=models.ImageField(default='/media/card.jfif', upload_to='posters/'),
        ),
    ]
