# Generated by Django 3.1.3 on 2021-01-31 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movies_poster'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostsForMainMenu',
        ),
        migrations.DeleteModel(
            name='Premyera',
        ),
        migrations.DeleteModel(
            name='Slider',
        ),
        migrations.AlterField(
            model_name='movies',
            name='movie',
            field=models.CharField(max_length=300),
        ),
    ]
