# Generated by Django 2.2.16 on 2021-01-18 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20210118_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Premyera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premyera_caption', models.CharField(max_length=100)),
                ('premyera_image', models.ImageField(upload_to='images/premyera/')),
            ],
        ),
        migrations.AlterModelOptions(
            name='movies',
            options={'verbose_name': 'movie', 'verbose_name_plural': 'movies'},
        ),
    ]
