# Generated by Django 2.2.16 on 2021-01-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20210118_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostsForMainMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=40)),
                ('post_author', models.CharField(max_length=50)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('post_description', models.TextField()),
                ('post_full_description', models.TextField()),
                ('post_image', models.ImageField(upload_to='images/postsformainmenu/')),
            ],
        ),
    ]
