# Generated by Django 3.1.3 on 2021-01-21 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20210120_1818'),
        ('movies', '0007_postsformainmenu'),
    ]

    operations = [
    ]
